import { beforeEach, describe, expect, it } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { createPinia } from 'pinia'
import { useAuthStore } from '@/stores/auth'
import type { User } from '@/types'
import StarterStories from './StarterStories.vue'
const create = (pinia = createPinia()) => mount(StarterStories, { global: { plugins: [pinia], stubs: { RouterLink: { template: '<a><slot /></a>' } } } })
describe('Tavern local story experience', () => {
  beforeEach(() => localStorage.clear())
  it('rejects an incompatible stored room without crashing or deleting it', () => {
    localStorage.setItem('tavern-local-room-v1-local', '{"scene":99}')
    const wrapper = create()
    expect(wrapper.find('.tavern-room-config').exists()).toBe(true)
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
    expect(localStorage.getItem('tavern-local-room-v1-local')).toBe('{"scene":99}')
    wrapper.unmount()
  })
  it('finishes a scripted experience when three choices are made', async () => {
    const wrapper = create()
    await wrapper.get('.tavern-room-config').trigger('submit')
    for (let step = 0; step < 3; step++) await wrapper.get('.tavern-choices button').trigger('click')
    await flushPromises()
    const saved = JSON.parse(localStorage.getItem('tavern-local-room-v1-local') ?? '{}')
    expect(saved.finished).toBe(true)
    expect(saved.choices).toHaveLength(3)
    expect(wrapper.find('.tavern-choices').exists()).toBe(false)
    wrapper.unmount()
  })
  it('restores the local room when remounted', async () => {
    const wrapper = create()
    await wrapper.get('.tavern-room-config').trigger('submit')
    await wrapper.get('.tavern-choices button').trigger('click')
    await flushPromises()
    wrapper.unmount()
    const restored = create()
    expect(restored.find('.tavern-play-room').exists()).toBe(true)
    expect(restored.findAll('.tavern-room-roster li')).toHaveLength(1)
    restored.unmount()
  })
  it('plays the second story with clues, a full decision history and a fresh restart', async () => {
    const wrapper = create()
    await wrapper.findAll('.tavern-story button')[1]!.trigger('click')
    await wrapper.get('.tavern-room-config').trigger('submit')
    expect(wrapper.get('.tavern-room-roster h2').text()).toBe('雾线末班车')
    await wrapper.get('.tavern-story-stage .tavern-start-link').trigger('click')
    expect(wrapper.get('blockquote').text()).toContain('旧塔、水闸、信号站')
    for (let step = 0; step < 3; step++) await wrapper.findAll('.tavern-choices button')[2]!.trigger('click')
    expect(wrapper.get('.tavern-story-stage h2').text()).toBe('本次体验结束')
    expect(wrapper.get('.tavern-narrative').text()).toContain('列车重新获得了方向')
    expect(wrapper.findAll('.tavern-room-roster li')).toHaveLength(3)
    expect(wrapper.text()).toContain('无 AI 调用')
    await wrapper.get('.tavern-story-stage .tavern-start-button').trigger('click')
    await wrapper.get('.tavern-room-config').trigger('submit')
    expect(wrapper.findAll('.tavern-room-roster li')).toHaveLength(0)
    expect(wrapper.get('.tavern-story-stage h2').text()).toBe('出发 · 消失的站牌')
    wrapper.unmount()
  })
  it('switches local saves by account without overwriting either journey', async () => {
    const pinia = createPinia()
    const auth = useAuthStore(pinia)
    auth.user = { id: 7, username: 'first' } as User
    const wrapper = create(pinia)
    await wrapper.get('.tavern-room-config').trigger('submit')
    await wrapper.get('.tavern-choices button').trigger('click')
    const firstSaved = localStorage.getItem('tavern-local-room-v1-7')
    auth.user = { id: 8, username: 'second' } as User
    await flushPromises()
    expect(wrapper.find('.tavern-room-config').exists()).toBe(true)
    await wrapper.findAll('.tavern-story button')[1]!.trigger('click')
    await wrapper.get('.tavern-room-config').trigger('submit')
    await wrapper.get('.tavern-choices button').trigger('click')
    expect(JSON.parse(localStorage.getItem('tavern-local-room-v1-8')!).storyId).toBe('fog-station')
    expect(localStorage.getItem('tavern-local-room-v1-7')).toBe(firstSaved)
    auth.user = { id: 7, username: 'first' } as User
    await flushPromises()
    expect(wrapper.get('.tavern-room-roster h2').text()).toBe('最后一封来信')
    expect(wrapper.get('.tavern-story-stage h2').text()).toContain('第二幕')
    expect(wrapper.findAll('.tavern-room-roster li')).toHaveLength(1)
    auth.user = null
    await flushPromises()
    expect(wrapper.find('.tavern-play-room').exists()).toBe(false)
    expect(localStorage.getItem('tavern-local-room-v1-7')).toBe(firstSaved)
    wrapper.unmount()
  })
  it('does not advance twice when a previous scene choice is clicked twice before rendering', async () => {
    const wrapper = create()
    await wrapper.get('.tavern-room-config').trigger('submit')
    const choice = wrapper.get('.tavern-choices button')
    choice.element.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    choice.element.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    await flushPromises()
    expect(wrapper.findAll('.tavern-room-roster li')).toHaveLength(1)
    expect(wrapper.get('.tavern-story-stage h2').text()).toContain('第二幕')
    wrapper.unmount()
  })
})
