package routes

import (
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/gin-gonic/gin"
)

func RegisterBizDecipherRoutes(
	v1 *gin.RouterGroup,
	h *handler.Handlers,
	jwtAuth middleware.JWTAuthMiddleware,
	adminAuth middleware.AdminAuthMiddleware,
	settingService *service.SettingService,
) {
	biz := v1.Group("/biz")
	{
		biz.GET("/pool/status", h.BizDecipher.GetPoolStatus)
		// Platform status bar: gateway-level health (channels & upstream
		// accounts), kept separate from the marketplace pool status.
		biz.GET("/platform/status", h.BizDecipher.GetPlatformStatus)
		// Account Square marketplace: public read-only browsing of shared pools.
		biz.GET("/models", h.BizDecipher.ListModelCatalog)
		biz.GET("/pools", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListSharedPools)
		biz.GET("/pools/:id", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetSharedPool)
		biz.GET("/pools/:id/pricing", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListSharedPoolModelPricing)
		biz.GET("/pools/:id/probe-histories", h.BizDecipher.ListSharedPoolProbeHistories)
		biz.GET("/pools/:id/full-check-report", h.BizDecipher.GetSharedPoolFullCheckReport)
		biz.GET("/assets", h.BizDecipher.ListCapabilityAssets)
		biz.GET("/assets/commerce-policy", h.BizDecipher.GetAssetCommercePolicy)
		biz.GET("/assets/:id", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetCapabilityAsset)
		biz.GET("/assets/:id/commerce", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetAssetCommerce)
		biz.GET("/assets/:id/versions", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListCapabilityAssetVersions)
		biz.GET("/tavern/scripts", h.BizDecipher.ListTavernScripts)
		biz.GET("/tavern/scripts/:id", h.BizDecipher.GetTavernScript)
		biz.GET("/tavern/scripts/:id/packages", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListTavernGamePackages)
		biz.GET("/community/posts", h.BizDecipher.ListCommunityPosts)
		biz.GET("/community/polls", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListCommunityPolls)
		biz.GET("/community/columns", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListCreatorColumns)
		biz.GET("/community/columns/:id", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetCreatorColumn)
		biz.GET("/community/columns/:id/articles", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.ListCreatorColumnArticles)
		biz.GET("/community/columns/:id/articles/:articleId", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetCreatorColumnArticle)
		biz.GET("/community/governance/rules", h.BizDecipher.ListGovernanceRules)
		biz.GET("/community/badges", h.BizDecipher.ListCommunityBadges)
		biz.GET("/community/users/:id/badges", h.BizDecipher.ListUserBadges)
		biz.GET("/community/shared-pool-summaries", h.BizDecipher.ListSharedPoolCommunitySummaries)
		biz.GET("/community/posts/:id/comments", h.BizDecipher.ListCommunityComments)
		biz.GET("/community/token-power", h.BizDecipher.GetTokenPowerLeaderboard)
		biz.GET("/market/listings", h.Marketplace.ListListings)
		biz.GET("/market/listings/:id", middleware.OptionalJWTAuth(jwtAuth), h.Marketplace.GetListing)
		biz.GET("/zero-city/profiles/:target", middleware.OptionalJWTAuth(jwtAuth), h.BizDecipher.GetZeroCityPublicProfile)
	}

	authenticated := v1.Group("/biz")
	authenticated.Use(gin.HandlerFunc(jwtAuth))
	authenticated.Use(middleware.BackendModeUserGuard(settingService))
	{
		authenticated.GET("/profile", h.BizDecipher.GetProfile)
		authenticated.PUT("/profile", h.BizDecipher.UpdateProfile)
		authenticated.GET("/workbench/workspace", h.BizDecipher.GetWorkbenchWorkspace)
		authenticated.GET("/harness/catalog", h.BizDecipher.ProxyHarness)
		authenticated.GET("/harness/models", h.BizDecipher.ProxyHarness)
		authenticated.POST("/harness/models", h.BizDecipher.ProxyHarness)
		authenticated.POST("/harness/run", h.BizDecipher.ProxyHarness)
		authenticated.POST("/workbench/runs", h.BizDecipher.CreateWorkbenchRun)
		authenticated.GET("/workbench/runs/:id", h.BizDecipher.GetWorkbenchRun)
		authenticated.GET("/workbench/runs/:id/artifact", h.BizDecipher.GetWorkbenchArtifact)
		authenticated.GET("/workbench/runs/:id/events", h.BizDecipher.StreamWorkbenchRunEvents)
		authenticated.POST("/workbench/runs/:id/fork", h.BizDecipher.ForkWorkbenchRun)
		authenticated.GET("/workbench/runs/:id/artifacts/:artifactId", h.BizDecipher.GetWorkbenchArtifactMetadata)
		authenticated.GET("/workbench/runs/:id/artifacts/:artifactId/content", h.BizDecipher.GetWorkbenchArtifactContent)
		authenticated.POST("/workbench/runs/:id/cancel", h.BizDecipher.CancelWorkbenchRun)
		authenticated.POST("/workbench/runs/:id/save", h.BizDecipher.SaveWorkbenchRun)
		authenticated.POST("/workbench/replays/:id/run", h.BizDecipher.ReplayWorkbenchRun)
		authenticated.GET("/credits", h.BizDecipher.ListMyCredits)
		authenticated.GET("/shared-pool/ledger", h.BizDecipher.ListMySharedPoolLedger)
		authenticated.GET("/shared-pool/usage-traces", h.BizDecipher.ListMySharedPoolUsageTraces)
		authenticated.GET("/shared-pool/ledger/earnings", h.BizDecipher.ListSharedPoolOwnerEarningsPage)
		authenticated.POST("/shared-pool/earnings/transfer", h.BizDecipher.TransferSharedPoolOwnerEarnings)
		authenticated.POST("/contributor/apply", h.BizDecipher.ApplyContributor)
		authenticated.POST("/operator/apply", h.BizDecipher.ApplyOperator)
		authenticated.POST("/custom-requests", h.BizDecipher.CreateCustomRequest)
		authenticated.POST("/market/listings", h.Marketplace.CreateListing)
		authenticated.PATCH("/market/listings/:id", h.Marketplace.UpdateListing)
		authenticated.POST("/market/listings/:id/archive", h.Marketplace.ArchiveListing)
		authenticated.GET("/market/my-listings", h.Marketplace.ListOwnerListings)
		authenticated.GET("/market/onboarding", h.Marketplace.GetOnboarding)
		authenticated.PUT("/market/onboarding", h.Marketplace.CompleteOnboarding)
		authenticated.POST("/market/listings/:id/inquiries", h.Marketplace.CreateInquiry)
		authenticated.GET("/market/inquiries", h.Marketplace.ListInquiries)
		authenticated.GET("/market/inquiries/:id/messages", h.Marketplace.ListMessages)
		authenticated.POST("/market/inquiries/:id/messages", h.Marketplace.PostMessage)
		authenticated.POST("/market/inquiries/:id/orders", h.Marketplace.QuoteOrder)
		authenticated.GET("/market/orders", h.Marketplace.ListOrders)
		authenticated.GET("/market/orders/:id", h.Marketplace.GetOrder)
		authenticated.POST("/market/orders/:id/actions", h.Marketplace.ApplyOrderAction)
		authenticated.GET("/chat/channels", h.Chat.ListChannels)
		authenticated.GET("/chat/channels/:slug/messages", h.Chat.ListMessages)
		authenticated.POST("/chat/channels/:slug/messages", h.Chat.SendMessage)
		authenticated.GET("/token-rewards/resources", h.Chat.RewardResources)
		authenticated.GET("/token-rewards/wallet", h.Chat.TokenRewardWallet)
		authenticated.POST("/token-rewards/runs", h.Chat.RunTokenReward)
		authenticated.GET("/token-rewards/reviews", middleware.AdminOnly(), h.Chat.ReviewTokenRewards)
		authenticated.POST("/token-rewards/reviews/:id/resolve", middleware.AdminOnly(), h.Chat.ResolveTokenReward)
		authenticated.GET("/chat/token-packets/:id", h.Chat.GetTokenPacket)
		authenticated.POST("/chat/token-packets/:id/claim", h.Chat.ClaimTokenPacket)
		authenticated.POST("/chat/channels/:slug/token-packets", middleware.AdminOnly(), h.Chat.CreateTokenPacket)
		authenticated.POST("/community/mascot-chat", h.BizDecipher.ChatCommunityMascot)
		authenticated.GET("/community/my-posts", h.BizDecipher.ListMyCommunityPosts)
		authenticated.GET("/community/participation", h.BizDecipher.GetCommunityParticipation)
		authenticated.GET("/my/assets", h.BizDecipher.ListMyCapabilityAssets)
		authenticated.GET("/my/assets/stats", h.BizDecipher.GetMyCapabilityAssetStats)
		authenticated.POST("/assets", h.BizDecipher.CreateCapabilityAsset)
		authenticated.PATCH("/assets/:id", h.BizDecipher.UpdateCapabilityAsset)
		authenticated.PATCH("/assets/:id/pricing", h.BizDecipher.SetAssetPricing)
		authenticated.POST("/assets/:id/purchases", h.BizDecipher.PurchaseAsset)
		authenticated.GET("/assets/:id/purchases", h.BizDecipher.ListAssetPurchases)
		authenticated.POST("/assets/:id/versions/:version/reuse", h.BizDecipher.ReuseCapabilityAssetPackage)
		authenticated.GET("/assets/:id/versions/:version/execution", h.BizDecipher.GetAssetExecutionPlan)
		authenticated.POST("/assets/:id/versions/:version/execution", h.BizDecipher.LaunchAssetExecution)
		authenticated.POST("/assets/:id/like", h.BizDecipher.SetCapabilityAssetLike)
		authenticated.DELETE("/assets/:id/like", h.BizDecipher.UnsetCapabilityAssetLike)
		authenticated.POST("/assets/:id/favorite", h.BizDecipher.SetCapabilityAssetFavorite)
		authenticated.DELETE("/assets/:id/favorite", h.BizDecipher.UnsetCapabilityAssetFavorite)
		authenticated.POST("/assets/:id/versions", h.BizDecipher.CreateCapabilityAssetVersion)
		authenticated.PUT("/assets/:id/versions/:version/files", h.BizDecipher.PutCapabilityAssetFile)
		// Local agent / CLI ingestion: validate and store a whole package in one call.
		authenticated.POST("/assets/:id/versions/:version/import", h.BizDecipher.ImportCapabilityAssetPackage)
		authenticated.POST("/assets/:id/versions/:version/finalize", h.BizDecipher.FinalizeCapabilityAssetVersion)
		authenticated.POST("/assets/:id/versions/:version/publish", h.BizDecipher.PublishCapabilityAssetVersion)
		authenticated.POST("/assets/:id/versions/:version/revoke", h.BizDecipher.RevokeCapabilityAssetVersion)
		authenticated.GET("/assets/:id/versions/:version/download", h.BizDecipher.DownloadCapabilityAssetPackage)
		authenticated.GET("/tavern/my-scripts", h.BizDecipher.ListMyTavernScripts)
		authenticated.GET("/tavern/commerce/policy", h.BizDecipher.GetTavernCommercePolicy)
		authenticated.PUT("/tavern/scripts/:id/pricing", h.BizDecipher.SetTavernScriptPricing)
		authenticated.GET("/tavern/rooms/:id/ticket", h.BizDecipher.GetTavernTicketQuote)
		authenticated.POST("/tavern/rooms/:id/ticket", h.BizDecipher.PurchaseTavernTicket)
		authenticated.POST("/tavern/rooms/:id/ticket/refund", h.BizDecipher.RefundTavernTicket)
		authenticated.POST("/tavern/scripts", h.BizDecipher.CreateTavernScript)
		authenticated.POST("/tavern/scripts/:id/packages", h.BizDecipher.CreateTavernGamePackage)
		authenticated.POST("/tavern/scripts/:id/packages/:version/publish", h.BizDecipher.PublishTavernGamePackage)
		authenticated.POST("/tavern/scripts/:id/packages/:version/revoke", h.BizDecipher.RevokeTavernGamePackage)
		authenticated.GET("/tavern/my-rooms", h.BizDecipher.ListMyTavernRooms)
		authenticated.POST("/tavern/rooms", h.BizDecipher.CreateTavernRoom)
		authenticated.GET("/tavern/rooms/:id/runtime", h.BizDecipher.GetTavernRoomRuntime)
		authenticated.GET("/tavern/rooms/:id/turns", h.BizDecipher.ListTavernRoomTurns)
		authenticated.POST("/tavern/rooms/:id/turns", h.BizDecipher.AppendTavernRoomTurn)
		authenticated.POST("/tavern/rooms/:id/ai-turns", h.BizDecipher.CreateTavernAITurn)
		authenticated.POST("/tavern/rooms/:id/runtime-session", h.BizDecipher.CreateTavernRuntimeSession)
		authenticated.POST("/tavern/runtime/session", h.BizDecipher.GetTavernRuntimeSession)
		authenticated.POST("/tavern/rooms/:id/open", h.BizDecipher.OpenTavernRoom)
		authenticated.POST("/tavern/rooms/:id/join", h.BizDecipher.JoinTavernRoom)
		authenticated.POST("/tavern/rooms/:id/start", h.BizDecipher.StartTavernRoom)
		authenticated.POST("/tavern/rooms/:id/complete", h.BizDecipher.CompleteTavernRoom)
		authenticated.POST("/tavern/rooms/:id/cancel", h.BizDecipher.CancelTavernRoom)
		authenticated.POST("/community/posts", h.BizDecipher.CreateCommunityPost)
		authenticated.POST("/community/polls", h.BizDecipher.CreateCommunityPoll)
		authenticated.POST("/community/columns", h.BizDecipher.CreateCreatorColumn)
		authenticated.PATCH("/community/columns/:id", h.BizDecipher.UpdateCreatorColumn)
		authenticated.POST("/community/columns/:id/articles", h.BizDecipher.CreateCreatorColumnArticle)
		authenticated.PATCH("/community/columns/:id/articles/:articleId", h.BizDecipher.UpdateCreatorColumnArticle)
		authenticated.POST("/community/polls/:id/vote", h.BizDecipher.VoteCommunityPoll)
		authenticated.POST("/community/polls/:id/close", h.BizDecipher.CloseCommunityPoll)
		authenticated.POST("/community/polls/:id/adopt", h.BizDecipher.AdoptCommunityPollAsRule)
		authenticated.PATCH("/community/posts/:id/action", h.BizDecipher.UpdateCommunityPostAction)
		authenticated.POST("/community/posts/:id/comments", h.BizDecipher.CreateCommunityComment)
		authenticated.POST("/zero-city/profiles/:userId/follow", h.BizDecipher.FollowZeroCityProfile)
		authenticated.DELETE("/zero-city/profiles/:userId/follow", h.BizDecipher.UnfollowZeroCityProfile)
		authenticated.PUT("/zero-city/profile/background", h.BizDecipher.UpdateZeroCityProfileBackground)
		// Promo campaigns: active campaign + claim state for the current user.
		authenticated.GET("/promo/active", h.BizDecipher.GetActivePromo)
		authenticated.POST("/promo/:id/claim", h.BizDecipher.ClaimPromo)
		// Pool seats (money-sensitive): join / leave a pool, list own seats.
		// NOTE: kept off the "/pools/:id" path to avoid a gin static-vs-wildcard
		// route conflict with the public GET "/pools/:id".
		authenticated.GET("/seats", h.BizDecipher.ListMySeats)
		authenticated.POST("/upstream/probe", h.BizDecipher.ProbeSharedPoolUpstream)
		authenticated.GET("/upstream/probe-jobs/:jobId", h.BizDecipher.GetSharedPoolProbeJob)
		authenticated.POST("/upstream/models", h.BizDecipher.FetchSharedPoolUpstreamModels)
		authenticated.POST("/pools", h.BizDecipher.CreateSharedPool)
		authenticated.POST("/pool-imports", h.BizDecipher.ImportSharedPools)
		authenticated.PATCH("/pools/:id", h.BizDecipher.UpdateSharedPool)
		authenticated.PUT("/pools/:id/pricing", h.BizDecipher.SaveSharedPoolCustomPrice)
		authenticated.DELETE("/pools/:id", h.BizDecipher.DeleteSharedPool)
		authenticated.PUT("/pools/:id/owner-pause", h.BizDecipher.SetSharedPoolOwnerPause)
		authenticated.GET("/my-pools", h.BizDecipher.ListMySharedPools)
		authenticated.GET("/owner/pools/:id/probe-histories", h.BizDecipher.ListOwnerSharedPoolProbeHistories)
		authenticated.GET("/pools/:id/accounts", h.BizDecipher.ListSharedPoolAccounts)
		authenticated.POST("/pools/:id/accounts", h.BizDecipher.CreateSharedPoolAccount)
		authenticated.POST("/pools/:id/accounts/import", h.BizDecipher.ImportSharedPoolAccounts)
		authenticated.POST("/pools/:id/accounts/import-oauth-package", h.BizDecipher.ImportSharedPoolOAuthPackage)
		authenticated.GET("/pools/:id/accounts/:accountId/probe-histories", h.BizDecipher.ListSharedPoolAccountProbeHistories)
		authenticated.PATCH("/pools/:id/accounts/:accountId", h.BizDecipher.UpdateSharedPoolAccount)
		authenticated.POST("/pools/:id/accounts/:accountId/native-readiness", h.BizDecipher.VerifySharedPoolNativeReadiness)
		authenticated.POST("/pools/:id/native-activation", h.BizDecipher.ActivateSharedPoolNativeBilling)
		authenticated.DELETE("/pools/:id/accounts/:accountId", h.BizDecipher.DeleteSharedPoolAccount)
		authenticated.GET("/share-keys", h.BizDecipher.ListMySharedPoolAccessKeys)
		authenticated.DELETE("/share-keys/:apiKeyId", h.BizDecipher.DeleteSharedPoolAccessKey)
		authenticated.POST("/pools/:id/access-key", h.BizDecipher.CreateSharedPoolAccessKey)
		authenticated.POST("/pools/:id/report", h.BizDecipher.ReportSharedPool)
		authenticated.POST("/pools/:id/like", h.BizDecipher.LikeSharedPool)
		authenticated.DELETE("/pools/:id/like", h.BizDecipher.UnlikeSharedPool)
		authenticated.GET("/pools/:id/members", h.BizDecipher.ListSharedPoolMembers)
		authenticated.DELETE("/pools/:id/members/:seatId", h.BizDecipher.RemoveSharedPoolMember)
		authenticated.POST("/pools/:id/join", h.BizDecipher.JoinSharedPool)
		authenticated.POST("/pools/:id/leave", h.BizDecipher.LeaveSharedPool)
		authenticated.PATCH("/pools/:id/card-skin", h.BizDecipher.SetPoolCardSkin)
		authenticated.DELETE("/pools/:id/card-skin", h.BizDecipher.ClearPoolCardSkin)
	}

	admin := v1.Group("/admin/biz")
	admin.Use(gin.HandlerFunc(adminAuth))
	admin.Use(middleware.AdminComplianceGuard(settingService))
	registerWalletWithdrawalRoutes(authenticated, admin, h)
	registerCreatorColumnCommerceRoutes(biz, authenticated, admin, h)
	registerMarketplaceFundsRoutes(authenticated, admin, h)
	{
		admin.GET("/contributors", h.BizDecipher.AdminListContributors)
		admin.GET("/operators", h.BizDecipher.AdminListOperators)
		admin.GET("/requests", h.BizDecipher.AdminListCustomRequests)
		admin.GET("/credits", h.BizDecipher.AdminListCreditLedger)
		admin.POST("/credits/grant", h.BizDecipher.AdminGrantCredit)
		admin.GET("/shared-pools", h.BizDecipher.AdminListSharedPools)
		admin.GET("/shared-pools/:id/pricing", h.BizDecipher.AdminInspectSharedPoolPricing)
		admin.GET("/shared-pool-owner-earnings", h.BizDecipher.AdminListSharedPoolOwnerEarnings)
		admin.GET("/shared-pool-usage-reviews", h.BizDecipher.AdminListSharedPoolUsageReviews)
		admin.GET("/shared-pool-usage-reviews/policy", h.BizDecipher.AdminGetSharedPoolUsageReviewPolicy)
		admin.PUT("/shared-pool-usage-reviews/policy", h.BizDecipher.AdminUpdateSharedPoolUsageReviewPolicy)
		admin.POST("/shared-pool-usage-reviews/batch-resolve", h.BizDecipher.AdminBatchResolveSharedPoolUsageReviews)
		admin.POST("/shared-pool-usage-reviews/:id/resolve", h.BizDecipher.AdminResolveSharedPoolUsageReview)
		admin.POST("/shared-pools/probe-aggregation", h.BizDecipher.AdminRunSharedPoolProbeAggregation)
		admin.GET("/shared-pools/:id/probe-histories", h.BizDecipher.AdminListSharedPoolProbeHistories)
		admin.GET("/shared-pools/:id/governance-logs", h.BizDecipher.AdminListSharedPoolGovernanceLogs)
		admin.PATCH("/shared-pools/:id/governance", h.BizDecipher.AdminUpdateSharedPoolGovernance)
		admin.POST("/shared-pools/:id/restore", h.BizDecipher.AdminRestoreSharedPool)
		admin.GET("/community/posts", h.BizDecipher.AdminListCommunityPosts)
		admin.PUT("/community/users/:id/participation", h.BizDecipher.AdminSetCommunityParticipation)
		admin.POST("/community/polls/:id/close", h.BizDecipher.AdminCloseCommunityPoll)
		admin.GET("/community/columns", h.BizDecipher.AdminListCreatorColumns)
		admin.PATCH("/community/columns/:id", h.BizDecipher.AdminModerateCreatorColumn)
		admin.POST("/community/governance/rules/:id/revoke", h.BizDecipher.AdminRevokeGovernanceRule)
		admin.POST("/community/badges/:key/grant", h.BizDecipher.AdminGrantCommunityBadge)
		admin.POST("/community/badges/:key/revoke", h.BizDecipher.AdminRevokeCommunityBadge)
		admin.GET("/assets", h.BizDecipher.AdminListCapabilityAssets)
		admin.PUT("/assets/commerce-policy", h.BizDecipher.AdminSetAssetCommercePolicy)
		admin.POST("/assets/:id/purchases/:purchaseId/refund", h.BizDecipher.AdminRefundAssetPurchase)
		admin.PATCH("/assets/:id/review", h.BizDecipher.AdminReviewCapabilityAsset)
		// Model capability matrix: declared modalities, adapter protocol and role.
		admin.PATCH("/models/:id/profile", h.BizDecipher.AdminUpdateModelCatalogProfile)
		admin.GET("/tavern/scripts", h.BizDecipher.AdminListTavernScripts)
		admin.PUT("/tavern/commerce/policy", h.BizDecipher.SetTavernCommercePolicy)
		admin.PATCH("/tavern/scripts/:id/review", h.BizDecipher.AdminReviewTavernScript)
		admin.PATCH("/community/posts/:id/status", h.BizDecipher.AdminUpdateCommunityPostStatus)
		admin.PATCH("/community/comments/:id/status", h.BizDecipher.AdminUpdateCommunityCommentStatus)
		admin.PATCH("/market/listings/:id/status", h.Marketplace.AdminSetListingStatus)
		admin.GET("/market/disputes", h.Marketplace.ListDisputes)
		admin.GET("/market/disputes/:id", h.Marketplace.GetDispute)
		admin.POST("/market/disputes/:id/resolve", h.Marketplace.ResolveDispute)
		// Promo campaign management (create / list / enable-disable / edit window & amount).
		admin.GET("/promos", h.BizDecipher.AdminListPromos)
		admin.POST("/promos", h.BizDecipher.AdminCreatePromo)
		admin.PATCH("/promos/:id", h.BizDecipher.AdminUpdatePromo)
	}
}
